project_id = "ifctpzrmqcpqtgwepvoq"

[functions.check-admin-access]
verify_jwt = false

[functions.sync-printify-products]
verify_jwt = false

[functions.cleanup-product-data]
verify_jwt = false

[functions.create-stripe-payment-intent]
verify_jwt = false

[functions.webhook-stripe]
verify_jwt = false

[functions.create-printify-order]
verify_jwt = false

[functions.verify-order-access]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.secure-contact-form]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.resend-order-email]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false
