project_id = "ifctpzrmqcpqtgwepvoq"

[functions.sync-printify-products]
verify_jwt = false

[functions.create-stripe-payment-intent]
verify_jwt = false

[functions.webhook-stripe]
verify_jwt = false

[functions.create-printify-order]
verify_jwt = false

[functions.verify-order-access]
verify_jwt = false